### ISSUE TITLE
Add obo file metadata to model

### ISSUE THREAD

**Issue by Freymaurer** [CSBiology/OBO.NET#26]
Maybe have a look what the most commonly used ontologies on obofoundry use

**Comment by omaus** [comment]
_Note:_

This is what is meant:

```yaml
format-version: 1.2
data-version: 2019-08-26
remark: Please see the project site https://github.com/BFO-ontology/BFO, the bfo2 owl discussion group http://groups.google.com/group/bfo-owl-devel, the bfo2 discussion group http://groups.google.com/group/bfo-devel, the tracking google doc http://goo.gl/IlrEE, and the current version of the bfo2 reference http://purl.obolibrary.org/obo/bfo/dev/bfo2-reference.docx. This ontology is generated from a specification at https://github.com/BFO-ontology/BFO/tree/master/src/ontology/owl-group/specification/ and with the code that generates the OWL version in https://github.com/BFO-ontology/BFO/tree/master/src/tools/. A very early version of BFO version 2 in CLIF is at http://purl.obolibrary.org/obo/bfo/dev/bfo.clif.
remark: The BSD license on the BFO project site refers to code used to build BFO.
remark: This BFO 2.0 version represents a major update to BFO and is not strictly backwards compatible with BFO 1.1. The previous OWL version of BFO, version 1.1.1 will remain available at http://ifomis.org/bfo/1.1 and will no longer be updated. The BFO 2.0 OWL is a classes-only specification. The incorporation of core relations has been held over for a later version.
ontology: bfo
property_value: http://purl.org/dc/elements/1.1/contributor "Alan Ruttenberg" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor "Albert Goldfain" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor "Barry Smith" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor "Bill Duncan" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor "Bjoern Peters" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor "Chris Mungall" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor "David Osumi-Sutherland" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor "Fabian Neuhaus" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor "Holger Stenzhorn" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor "James A. Overton" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor "Janna Hastings" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor "Jie Zheng" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor "Jonathan Bona" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor "Larry Hunter" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor "Leonard Jacuzzo" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor "Ludger Jansen" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor "Mark Ressler" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor "Mathias Brochhausen" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor "Mauricio Almeida" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor "Melanie Courtot" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor "Pierre Grenon" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor "Randall Dipert" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor "Ron Rudnicki" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor "Selja Seppälä" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor "Stefan Schulz" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor "Thomas Bittner" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor "Werner Ceusters" xsd:string
property_value: http://purl.org/dc/elements/1.1/contributor "Yongqun \"Oliver\" He" xsd:string
property_value: http://purl.org/dc/terms/license http://creativecommons.org/licenses/by/4.0/
property_value: http://xmlns.com/foaf/0.1/homepage http://basic-formal-ontology.org/
property_value: http://xmlns.com/foaf/0.1/homepage http://ifomis.org/bfo
property_value: http://xmlns.com/foaf/0.1/homepage https://github.com/BFO-ontology/BFO
property_value: http://xmlns.com/foaf/0.1/mbox mailto:bfo-owl-devel@googlegroups.com
property_value: IAO:0000116 "BFO 2 Reference: BFO does not claim to provide complete coverage of entities of all types. It seeks only to provide coverage of those entities studied by empirical science together with those entities which affect or are involved in human activities such as data processing and planning - coverage that is sufficiently broad to provide assistance to those engaged in building domain ontologies for purposes of data annotation." xsd:string
property_value: IAO:0000116 "BFO 2 Reference: BFO's treatment of continuants and occurrents - as also its treatment of regions, rests on a dichotomy between space and time, and on the view that there are two perspectives on reality - earlier called the 'SNAP' and 'SPAN' perspectives, both of which are essential to the non-reductionist representation of reality as we understand it from the best available science." xsd:string
property_value: IAO:0000116 "BFO 2 Reference: For both terms and relational expressions in BFO, we distinguish between primitive and defined. 'Entity' is an example of a  primitive term. Primitive terms in a highest-level ontology such as BFO are terms that are so basic to our understanding of reality that there is no way of defining them in a non-circular fashion. For these, therefore, we can provide only elucidations, supplemented by examples and by axioms." xsd:string
property_value: isDefinedBy http://purl.obolibrary.org/obo/bfo/dev/bfo.clif
property_value: isDefinedBy https://github.com/BFO-ontology/BFO/tree/master/src/ontology/owl-group/specification/
property_value: seeAlso http://groups.google.com/group/bfo-devel
property_value: seeAlso http://groups.google.com/group/bfo-discuss
property_value: seeAlso http://groups.google.com/group/bfo-owl-devel
property_value: seeAlso http://purl.obolibrary.org/obo/bfo/dev/owl
property_value: seeAlso https://github.com/BFO-ontology/BFO/tree/master/src/tools/
owl-axioms: Prefix(owl:=<http://www.w3.org/2002/07/owl#>)\nPrefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>)\nPrefix(xml:=<http://www.w3.org/XML/1998/namespace>)\nPrefix(xsd:=<http://www.w3.org/2001/XMLSchema#>)\nPrefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>)\n\n\nOntology(\nDeclaration(Class(<http://purl.obolibrary.org/obo/BFO_0000001>))\nDeclaration(AnnotationProperty(<http://purl.obolibrary.org/obo/BFO_0000179>))\nDeclaration(AnnotationProperty(<http://purl.obolibrary.org/obo/BFO_0000180>))\n############################\n#   Annotation Properties\n############################\n\n# Annotation Property: <http://purl.obolibrary.org/obo/BFO_0000179> (BFO OWL specification label)\n\nSubAnnotationPropertyOf(<http://purl.obolibrary.org/obo/BFO_0000179> rdfs:label)\n\n# Annotation Property: <http://purl.obolibrary.org/obo/BFO_0000180> (BFO CLIF specification label)\n\nSubAnnotationPropertyOf(<http://purl.obolibrary.org/obo/BFO_0000180> rdfs:label)\n\n\n############################\n#   Classes\n############################\n\n# Class: <http://purl.obolibrary.org/obo/BFO_0000001> (entity)\n\nSubClassOf(<http://purl.obolibrary.org/obo/BFO_0000001> owl:Thing)\n\n\n)
```

(taken from https://raw.githubusercontent.com/BFO-ontology/BFO/v2019-08-26/bfo_classes_only.obo)

s. here: https://owlcollab.github.io/oboformat/doc/GO.format.obo-1_4.html#S.2
